sync-engine:
  #build: .
  #dockerfile: Dockerfile
  image: nhurel/nylas-sync-engine
  ports:
    - 5000:5000
  links:
    - mysql:mysql

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
